---
apiVersion: v1
kind: Namespace
metadata:
   name: trident
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-installer
  namespace: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: trident-installer
  namespace: trident
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trident-backend-checker
  namespace: trident
spec:
  template:
    spec:
      serviceAccountName: trident-installer
      containers:
      - name: trident-backend-checker
        image: fabianborn/dev-trident-installer:20.07.1
        volumeMounts:
          - name: manifests
            mountPath: /manifests
        command: ["/bin/sh"]
        args: ["/manifests/install.sh"]
      restartPolicy: OnFailure
      volumes:
        - name: manifests
          configMap:
            name: trident-backend-checker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-backend-checker
  namespace: trident
data:
  install.sh: |-
    set -ex
    sleep 3 
    /opt/trident-installer/tridentctl get backend -n trident -o json > /export/tbe.json
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tbe-checker
  namespace: trident
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tbe-checker
            image: fabianborn/dev-trident-installer:20.07.1
            volumeMounts:
              - name: manifests
                mountPath: /manifests
              - mountPath: /export
                name: export-json      
            command: ["/bin/sh"]
            args: ["/manifests/install.sh"]
          restartPolicy: OnFailure
          volumes:
            - name: manifests
              configMap:
                name: trident-backend-checker
            - emptyDir: {}
              name: export-json
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
