---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-installer
  namespace: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: trident-installer
  namespace: trident
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sc_access
rules:
- apiGroups: ["storage.k8s.io", "core" ]
  resources: [ "storageclass" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-sc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sc_access
subjects:
- kind: ServiceAccount
  name: trident-installer
  namespace: kube-systems
