---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-backend-checker
  namespace: trident
data:
  run.sh: |-
    set -ex
    sleep 3
    /opt/trident-installer/tridentctl -n trident get backend -o json > /tmp/current.json
    kubectl get configmap -n trident tbe-data -o jsonpath='{.data.tbe-data-current\.json}' > /tmp/new-last.json
    kubectl get configmap -n trident tbe-data -o jsonpath='{.data.tbe-data-last\.json}' > /tmp/last.json

    if (cmp /tmp/current.json /tmp/new-last.json)
    then
      echo "No Config change"
      if (cmp /tmp/new-last.json /tmp/last.json)
      then
        echo "nothing!"
      else
        kubectl create configmap -n trident tbe-data --from-file=tbe-data-current.json=/tmp/last.json --from-file=tbe-data-last.json=/tmp/new-last.json --dry-run=client -o yaml | kubectl apply -f -
      fi 
    else
      echo "The files are different"
      kubectl create configmap -n trident tbe-data --from-file=tbe-data-current.json=/tmp/current.json --from-file=tbe-data-last.json=/tmp/new-last.json --dry-run=client -o yaml    
      kubectl create configmap -n trident tbe-data --from-file=tbe-data-current.json=/tmp/current.json --from-file=tbe-data-last.json=/tmp/new-last.json --dry-run=client -o yaml | kubectl apply -f -
    fi
    cat /tmp/new-last.json 

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tbe-checker
  namespace: trident
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: trident-installer
          containers:
          - name: tbe-checker
            image: fabianborn/dev-trident-installer:20.07.1
            volumeMounts:
              - name: manifests
                mountPath: /manifests
            command: ["/bin/sh"]
            args: ["/manifests/run.sh"]
          restartPolicy: OnFailure
          volumes:
            - name: manifests
              configMap:
                name: trident-backend-checker
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
